# core/report_generator.py

from fpdf import FPDF
from datetime import datetime

class AuditReport(FPDF):
    def header(self):
        # Professional Header
        self.set_font("helvetica", "B", 16)
        self.cell(0, 10, "Sentinel-Trace | Digital Footprint Intelligence", border=False, align="C")
        self.ln(15)

    def footer(self):
        # Professional Footer
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        # Adding a professional signature to the generated reports
        self.cell(0, 10, f"Page {self.page_no()} | Generated by Sentinel-Trace | Lead Researcher: Ahmad Abu Zayed", align="C")

def generate_pdf_report(save_path, target_username, score, results):
    """Generates the PDF and saves it to the chosen directory."""
    pdf = AuditReport()
    pdf.add_page()
    
    # Report Metadata
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(50, 8, "Target Username:", border=0)
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, target_username, border=0, ln=True)

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(50, 8, "Date of Audit:", border=0)
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, datetime.now().strftime("%Y-%m-%d %H:%M:%S"), border=0, ln=True)

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(50, 8, "Privacy Health Score:", border=0)
    
    # Color code the score in the PDF
    if score >= 75:
        pdf.set_text_color(47, 165, 114)  # Green
    elif score >= 50:
        pdf.set_text_color(229, 149, 0)   # Yellow
    else:
        pdf.set_text_color(230, 57, 70)   # Red
        
    pdf.cell(0, 8, f"{score}%", border=0, ln=True)
    pdf.set_text_color(0, 0, 0) # Reset to black
    
    pdf.line(10, pdf.get_y() + 5, 200, pdf.get_y() + 5)
    pdf.ln(12)

    # Exposures Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Discovered Surface Area", ln=True)
    pdf.set_font("helvetica", "", 11)

    if not results:
        pdf.cell(0, 8, "No linked accounts were discovered on monitored platforms. Excellent privacy posture.", ln=True)
    else:
        pdf.cell(0, 8, f"Warning: {len(results)} potential profile exposures detected.", ln=True)
        pdf.ln(5)
        
        # Table Header
        pdf.set_font("helvetica", "B", 11)
        pdf.set_fill_color(200, 200, 200)
        pdf.cell(40, 8, "Platform", border=1, fill=True)
        pdf.cell(150, 8, "Confirmed URL", border=1, fill=True, ln=True)
        
        # Table Data
        pdf.set_font("helvetica", "", 10)
        for account in results:
            pdf.cell(40, 8, account['site'], border=1)
            pdf.cell(150, 8, account['url'], border=1, ln=True)

    # Save to the user's chosen directory
    pdf.output(save_path)
